<?php
/** @var Network\AskForProduct\Block\AskForm $block */
$product = $block->getProduct();
$productUrl = $product->getUrlModel()->getUrlInStore($product, ['_ignore_category' => true]);
$sku = $product->getSku();
$customerName = $block->getCustomerName();
$customerEmail = $block->getCustomerEmail();
$logoImage = $block->getLogoImage();
$headerText = $block->getHeaderText();
$subtext = $block->getSubtext();
?>
<div class="ask-for-product">
    <div id="ask-for-product-button">
        <?php if ($logoImage): ?>
            <img src="<?php echo $logoImage; ?>" alt="Logo" class="ask-for-product-logo"/>
        <?php endif; ?>
        <div  class="ask-for-product-header" type="button"><?php echo __($headerText); ?></div>
        <?php if ($subtext): ?>
            <div class="ask-for-product-subtext"><?php echo __($subtext); ?></div>
        <?php endif; ?>
    </div>
    <div id="ask-for-product-modal" class="ask-for-product-modal" style="display: none;">
        <form id="ask-for-product-form" action="<?php echo $block->getFormAction(); ?>" method="post">
            <input type="hidden" name="sku" value="<?php echo $sku; ?>">
            <input type="hidden" name="product_link" value="<?php echo $productUrl; ?>">
            <div class="fieldset">
                <div class="field field-name required">
                    <label for="name"><?php echo __('Name'); ?></label>
                    <input type="text" disabled id="name" name="name" class="required-entry" value="<?php echo $customerName; ?>" required>
                </div>
                <div class="field field-mail required">
                    <label for="email"><?php echo __('Email'); ?></label>
                    <input type="email" disabled id="email" name="email" class="required-entry validate-email" value="<?php echo $customerEmail; ?>" required>
                </div>
                <div class="field field-important required" style="display:none !important;">
                    <input type="text" name="isimportant" value="">
                </div>
                <div class="field field-message required">
                    <label for="message"><?php echo __('Message'); ?></label>
                    <textarea id="message" disabled name="message" class="required-entry" required></textarea>
                </div>
            </div>
        </form>
    </div>
</div>
